[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "symbolicai"
dynamic = ["version"]
authors = [
    {name = "Marius-Constantin Dinu", email = "office@alphacoreai.eu"},
]
description = "A Neuro-Symbolic Framework for Python"
readme = "README.md"
requires-python = ">=3.7"
keywords = ["symbolic programming", "machine learning"]
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "natsort", "numpy", "tqdm", "python-box", "wolframalpha",
    "scikit-learn", "torch", "torchvision", "pyyaml", "transformers", 
    "openai", "google-search-results", "PyPDF2", "ipython",
    "beautifulsoup4", "selenium", "webdriver-manager", "whisper"
]

[tool.setuptools.dynamic]
version = {attr = "symai.SYMAI_VERSION"}

[tool.setuptools.package-data]
"*" = ["*.json"]

[tool.setuptools.packages.find]
include = ["symai", "bin"]
exclude = ["bin/ffmpeg-git-20220910-amd64-static", "tests", "examples", "notebooks", "outputs", "assets"]

[project.urls]
"Homepage" = "https://alphacoreai.eu/"
"GitHub" = "https://github.com/Xpitfire/symai"
